repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6 # Updated to match pyproject.toml
    hooks:
      - id: ruff
        args: [--fix, --show-source] # Added --show-source for better output
      - id: ruff-format
        args: [--respect-gitignore]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: debug-statements
      - id: check-case-conflict
      - id: mixed-line-ending
        args: [--fix=lf] 